server:
  port: 9090

#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SpringDataJPA
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#  flyway:
#    locations=classpath: db/migration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect


